### ISSUE TITLE
Only the first page gets converted to tiff format, but not the second

### ISSUE THREAD

**Issue by Legends** [aspose-pdf/Aspose.PDF-for-.NET#11]
Following this gist, i would expect that pages of the pdf will result in one tiff file:

https://gist.github.com/aspose-pdf/7e1330795d76012fcb04248bb81d45b3#file-examples-csharp-asposepdf-images-allpagestotiff-allpagestotiff-cs

What happens, only the first page gets converted to tiff format.

`<package id="Aspose.PDF" version="20.1.0" targetFramework="net48" />`

**Comment by kashifiqb** [comment]
@Legends ,

We were not able to reproduce this issue at our end as the output contains all the 3 TIFF pages as converted from the input PDF file. You can observe the same in this [screenshot](https://prnt.sc/qra3kh). I have tried the same at my end with Aspose.PDF for .NET v 20.1.0.  In case you still face the issue, please post your sample console project in [Aspose.PDF forum](https://forum.aspose.com/c/pdf) to get further assistance in this regard.

**Comment by Legends** [comment]
I guess, I don't have the right application installed in order to view a multi-page tiff file and therefore it only shows the first page when using `Windows Fotos`?!

But when I right-click the tiff file --> convert to pdf --> it shows all pages.
So it's related to my file viewer here.
