### ISSUE TITLE
How to Add pencil Tool

### ISSUE THREAD

**Issue by softtechinfo2020** [aspose-pdf/Aspose.PDF-for-.NET#12]
How to add pencil tool like paint.Anyone can please help.

**Comment by tahir-manzoor** [comment]
@softtechinfo2020 

You can use classes of [Aspose.Pdf.Drawing](https://apireference.aspose.com/pdf/net/aspose.pdf.drawing) to create shapes. Could you please share some more detail about your requirement along with sample expected output PDF?

**Comment by ilyazhuykov** [comment]
Since there have been no updates or additional questions for more than half a year, the issue is considered resolved.
