### ISSUE TITLE
Prevent object from dragging outside of canvas

### ISSUE THREAD

**Issue by yjadhav** [aspose-pdf/Aspose.PDF-for-.NET#14]
I am using AsposePdfEditor solution.
I have added image on canvas and try to moving on canvas.
While dragging the image on canvas there is no prevention from dragging outside of canvas.
Please suggest how to do it.

**Comment by farhan-raza** [comment]
Please note that HTML5 browser editor was just a demonstration of how you can use Aspose.PDF rendering features in your web application, not a service or product of Aspose. It has been discontinued, so we are afraid that any further development or enhancement in HTML5 editor application might not be available. 
**PS:** I work with Aspose as Developer Evangelist.

**Comment by farhan-raza** [comment]
@yjadhav, Please note that HTML5 browser editor was just a demonstration of how you can use Aspose.PDF rendering features in your web application, not a service or product of Aspose. It has been discontinued, so we are afraid that any further development or enhancement in HTML5 editor application might not be available.
PS: I work with Aspose as Developer Evangelist.
