### ISSUE TITLE
Edit existing PDF using aspose PDF in .net C#

### ISSUE THREAD

**Issue by VishalD10** [aspose-pdf/Aspose.PDF-for-.NET#16]
I want to grab existing PDF file and edit it using Aspose .I have attached the images of source and expected PDF
[source.pdf](https://github.com/aspose-pdf/Aspose.PDF-for-.NET/files/5385916/source.pdf)
[Expected.pdf](https://github.com/aspose-pdf/Aspose.PDF-for-.NET/files/5385919/Expected.pdf)

**Comment by asadalikhan90** [comment]
@VishalD10 

For such layout in PDF documents, we recommend using Acroforms as filling values would be easy using them. You can [add form fields](https://docs.aspose.com/pdf/net/working-with-forms/) in the source PDF and use it as template to gather information. Aspose.PDF for .NET can be used to [fill the forms.](https://docs.aspose.com/pdf/net/working-with-forms/) In case you do not have form fields, you can [add text using Aspose.PDF](https://docs.aspose.com/pdf/net/working-with-text/) and this way you will need proper location and coordinates of the source PDF where the text should be placed.

In case of any issues, please create a topic in [Aspose.PDF official support forum](https://forum.aspose.com/c/pdf) where you will be assisted accordingly.

**Comment by arise-project** [comment]
Hello, @VishalD10. We added latest version of an editor to folder https://github.com/aspose-pdf/Aspose.PDF-for-.NET/tree/master/Showcases/aspose-pdf-editor

**Comment by ilyazhuykov** [comment]
Since there have been no updates or additional questions for more than half a year, the issue is considered resolved.
