### ISSUE TITLE
add Multiple Signatures on a Single PDF

### ISSUE THREAD

**Issue by bluetianx** [aspose-pdf/Aspose.PDF-for-.NET#16]
I want to add multiple signatures on a single Pdf. My code as follows  `System.Drawing.Rectangle rect = new System.Drawing.Rectangle(100, 100, 100, 100);

            PKCS1 signature = new PKCS1(@"eamsT.sinopec.com.pfx", "20180201");
            PdfFileSignature pdfSign = new PdfFileSignature(new Document(@"input.pdf"));
            pdfSign.SignatureAppearance = "test.png";
            pdfSign.Sign(1, "Signature Reason", "Contact", "Location", true, rect, signature);
            pdfSign.Save(@"output.pdf");
            pdfSign.Close();
            rect = new System.Drawing.Rectangle(260, 260, 100, 100);

            PKCS1 signature2 = new PKCS1(@"eamsT.sinopec.com.pfx", "20180201");
            pdfSign = new PdfFileSignature(new Document(@"output.pdf"));
            pdfSign.SignatureAppearance = "test.png";
            pdfSign.Sign(1, " Reason2", "Contact", "Location", true, rect, signature2);
            pdfSign.Save(@"output.pdf");
            pdfSign.Close();`

There is a problem that  my reader  (Adobe Acrobat Reader DC)tells me that Signature verification statusThe signature is invalid.The document has been altered or corrupted since the signature was applied.

**Comment by farhan-raza** [comment]
@bluetianx , Would you please share all the resources including source and generated PDF file, PFX file and a screenshot displaying the problem in Adobe Acrobat DC. So that we may try to reproduce and investigate your scenario exactly, to help you out. Before sharing request data via Google Drive, Dropbox etc, please ensure using [Aspose.PDF for .NET 18.8](https://www.nuget.org/packages/Aspose.Pdf/18.8.0) in your environment.

PS: I work with Aspose as Developer Evangelist.

**Comment by bluetianx** [comment]
sorroy, i cannot user Google Drive,I upload resouces in my github [github](https://github.com/bluetianx/AsposePDFTest),  You can run method TestMethod1() of UnitTestConsole project,then  you can the output pdf file in AsposePDFTest\TechLab\UnitTestConsole\bin\Debug\netcoreapp2.0.

**Comment by bluetianx** [comment]
The version of acrobat that I use is 18.011.20058.33888

**Comment by farhan-raza** [comment]
@bluetianx , Thank you for sharing requested resources. We have logged a ticket with ID **PDFNET-45257** in our issue management system for further investigation and resolution. We will update you as soon as some significant updates will be available. 

We are sorry for the inconvenience.

**Comment by bluetianx** [comment]
Alright 。thanks
