### ISSUE TITLE
Does Aspose.Pdf not support Chinese?

### ISSUE THREAD

**Issue by 16cm** [aspose-pdf/Aspose.PDF-for-.NET#20]
Q：Pdf does not support Chinese it? Will it be supported in the future?
operation：html to pdf...
version: aspose.pdf 21.5
platform：net 5.0

```C#
public static void ConvertHTMLtoPDFAdvanced_WebPage()
{
    const string url = @"https://mp.weixin.qq.com/s/dWGzQI5mdmItVXcuxVLOQA";
    HtmlLoadOptions options = new HtmlLoadOptions(url) {};
    Document pdfDocument = new Document(GetContentFromUrlAsStream(url), options);
    pdfDocument.Save(AppDomain.CurrentDomain.BaseDirectory + "html_test.PDF");
}

private static Stream GetContentFromUrlAsStream(string url, ICredentials credentials = null)
{
    using (var handler = new HttpClientHandler { Credentials = credentials })
    using (var httpClient = new HttpClient(handler))
    {
        return httpClient.GetStreamAsync(url).GetAwaiter().GetResult();
    }
}
```

![2021-05-20_23-46-33.png](https://i.loli.net/2021/05/20/jVkTpcZHqgSIGei.png)

**Comment by tahir-manzoor** [comment]
@ijrou 

Aspose.PDF does support Chinese. Please use the latest version of [Aspose.PDF for .NET 22.5](https://www.nuget.org/packages/Aspose.PDF/22.5). You need to install the fonts used in your HTML on the machine where you are converting HTML to PDF.

**Comment by ilyazhuykov** [comment]
I couldn't reproduce directly with provided code - there was missing content in result file 
As user didn't mentioned such issues, I downloaded original page https://mp.weixin.qq.com/s/dWGzQI5mdmItVXcuxVLOQA as "chinese_issue.htm" and used the following test:
    
        public static void ConvertHTMLtoPDFAdvanced_WebPage()
        {
            var input = InputFolder + "chinese_issue.htm";
            HtmlLoadOptions options = new HtmlLoadOptions();
            Document pdfDocument = new Document(input, options);
            pdfDocument.Save(OutputFolder + "chinese_issue_out.pdf");
        }

With adjustments I checked that original issue is resolved and there's no broken characters in result file

[chinese_issue_out.pdf](https://github.com/user-attachments/files/18065956/chinese_issue_out.pdf)
As original question was about absence of support of Chinese in Aspose Pdf, I consider issue as resolved
