### ISSUE TITLE
System.Drawing.Common is deprecated on non-Windows platforms

### ISSUE THREAD

**Issue by safern** [aspose-pdf/Aspose.PDF-for-.NET#21]
Hello, I work on the .NET Libraries team, and I saw that this library has a lot of usage in the community and depends on System.Drawing.Common for xplat scenarios.

We made the decision to make `System.Drawing.Common` a windows only library starting .NET6+ due to a lot of reasons after a long discussion. You can see more details here:
https://github.com/dotnet/designs/blob/a15a8c7a324c482c5e38b73e46c2afe56f6bd504/accepted/2021/system-drawing-win-only/system-drawing-win-only.md

Also: https://github.com/dotnet/docs/issues/25257

We wanted to reach out so that you could react to this changes when .NET 6 is released. Also if you have any questions/concerns please do let us know at https://github.com/dotnet/runtime

What is the recommended action to still support winforms/wpf scenarios for example?

You can mark the APIs that need to use System.Drawing.Common to support winforms/wpf as windows only using the `SupportedOSPlatform("windows")` annotation, and then add new APIs that use another library like `ImageSharp` or `SkiaSharp.

**Comment by asadalikhan90** [comment]
@safern 

Thanks for sharing your concerns. We would like to share with you that we have already taken this scenario into account and have been working on replacing the System.Drawing.Commong dependency from Aspose.PDF for .NET. The task has been logged under the ticket ID **PDFNET-50918** which has been linked to a [thread](https://forum.aspose.com/t/net-6-support-missing-for-aspose-cells-aspose-imaging-aspose-pdf-aspose-slides-net-on-macos-linux/246463/) in our official support forum where progress of this task can be tracked. We will surely announce in the linked thread as soon as the ticket is resolved.

**Comment by arise-project** [comment]
Hello, @safern , could you please, look to Aspose.Pdf.Drawing library. It has no System.Drawing dependency.

**Comment by ilyazhuykov** [comment]
Task PDFNET-50918 is closed, currently we have Aspose Pdf Drawing as solution for Linux OS environments
