### ISSUE TITLE
AddSVGObject doesn't work with 21.9.0

### ISSUE THREAD

**Issue by dirq** [aspose-pdf/Aspose.PDF-for-.NET#22]
The SVG is not embedded/displayed in the output PDF.
![image](https://user-images.githubusercontent.com/429648/135644708-8aec915c-4d1d-4e33-bae4-af1bc899827c.png)

**Comment by tahir-manzoor** [comment]
@dirq 

Please use the latest version of [Aspose.PDF for .NET 22.5](https://www.nuget.org/packages/Aspose.PDF/22.5). If you still face problem, please share your input SVG and code example here for testing. We will investigate the issue and provide you more information on it.

**Comment by ilyazhuykov** [comment]
Since there have been no updates or additional questions for more than half a year, the issue is considered resolved.
