### ISSUE TITLE
Can't run in dotnet6

### ISSUE THREAD

**Issue by YouthCodeChen** [aspose-pdf/Aspose.PDF-for-.NET#23]
at “new Aspose.Pdf.License().SetLicense(key)“  Throw an exception。

**Comment by tahir-manzoor** [comment]
@YouthCodeChen 

The latest version of Aspose.PDF for .NET 22.5 does support .NET 6.0. So, please use the latest version of [Aspose.PDF for .NET 22.5](https://www.nuget.org/packages/Aspose.PDF/22.5).
