### ISSUE TITLE
How to run the demo sample?

### ISSUE THREAD

**Issue by sang2357** [aspose-pdf/Aspose.PDF-for-.NET#29]
I compiled the demo sample [(https://github.com/aspose-pdf/Aspose.PDF-for-.NET/tree/master/Demos)](https://github.com/aspose-pdf/Aspose.PDF-for-.NET/tree/master/Demos) but I cannot run it as it has no default page. According to the document as below, there should have a Default page. I also tried to create a web form based on the mater page file "site.Master" but it shows blank. Would anyone know how to run this sample?

> How to run
> 
> 1. Clone the repository
> 2. Open the solution file in the latest version of Microsoft Visual Studio.
> 3. Set Default as start page
> 4. Build the solution

**Comment by arise-project** [comment]
Hello, @sang2357. We have published new instruction for demo sample. Take a look on windows instructions we added: https://github.com/aspose-pdf/Aspose.PDF-for-.NET/blob/master/Demos/README.md

**Comment by ilyazhuykov** [comment]
Instruction is updated, since there's no new questions for a year long period issue considered as closed
