### ISSUE TITLE
PROBLEM ON LINUX DEBIAN 

### ISSUE THREAD

**Issue by BorisDmv** [aspose-pdf/Aspose.PDF-for-.NET#30]
If I run locally it works on Windows but just simple example with text hello world and it crashes always on document.Save

Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'key')

**Comment by asadalikhan90** [comment]
@BorisDmv 

We apologize for the delayed response. Would you kindly try now with the latest version of Aspose.PDF.Drawing package instead of Aspose.PDF. You can simply install it through NuGet package manager and run the project. In case issue still persists, please let us know.

**Comment by ilyazhuykov** [comment]
Since there have been no updates or additional questions for more than half a year, the issue is considered resolved.
