### ISSUE TITLE
Does not exist in the namespace System.Web.UI in .NET 4.8 error fix

### ISSUE THREAD

**Issue by Adephx** [aspose-pdf/Aspose.PDF-for-.NET#41]
Add `System.Web.Extensions` to the references.

**Comment by asadalikhan90** [comment]
@Adephx 

Thanks for pointing this out. We will definitely consider it while updating the code here. However, we request you please create a post in our[ official support forum](https://forum.aspose.com/c/pdf) which is the right place to post such issues and track their progress appropriately.

**Comment by arise-project** [comment]
Hello, @Adephx it seems to me, we already remove obsolete System.Wen.UI from all projects and replaced it with System.Web.Extensions

**Comment by ilyazhuykov** [comment]
Described error doesn't seem to be present in current(24.11) & old (23.7) versions  of Aspose.Pdf
as there have been no updates & description why System.Web.Extensions is necessary for problem solution, issue considered resolved
