### ISSUE TITLE
Why pdf viewer does not have button-"drop&Drop or upload your files" ? and Can this be used?

### ISSUE THREAD

**Issue by John-zzx** [aspose-pdf/Aspose.PDF-for-.NET#52]
![Uploading 1700727200259.jpg…]()
I have run the "Demos" on local ,but why it does not support to upload files ?and all the apps don't have this, ls this can be used? I want
to refer this demo to develop an individual "pdf viewer" app. 
Expect your reply!

**Comment by arise-project** [comment]
Hello @John-zzx, could you explain, how to reproduce an error with Demos? I tested viewer and can drop file to see content. You may need to install prerequisites for IIS to run Demo project. We also have an editor for dotnet core, it does not depend on Windows components.

![image](https://github.com/aspose-pdf/Aspose.PDF-for-.NET/assets/6891477/763a5eaa-4f81-4884-9d02-c64825259e9d)

**Comment by arise-project** [comment]
Hello @John-zzx I reviewed a license on the top of repository. It set to MIT, you can use all complete demo or any code snippets to your product. I also willing to share a link to an editor demo .Net 7.0:
https://github.com/aspose-pdf/Aspose.PDF-for-.NET/tree/master/Showcases/aspose-pdf-editor

**Comment by ilyazhuykov** [comment]
Tested locally, it seems that drag&drop requires to do following steps:
1. Open upload window
![image](https://github.com/user-attachments/assets/028dcb7a-4f5f-4552-8b59-3384747ab714)
2. Drag& drop file into this area
![image](https://github.com/user-attachments/assets/c710f451-e96c-416b-98cc-1b4fe1721ed6)
3.Success!
![image](https://github.com/user-attachments/assets/18aeaee2-f844-47e5-bf3b-db3599e1077e)

If file is moved just directly or outside the area, then viewer is replaced with dragged document

Issue seems to be resolved, as there have been no updates for more than a year, it considered closed
