### ISSUE TITLE
Adding text, images, and signatures to a PDF doesn't work

### ISSUE THREAD

**Issue by armaanrustami** [aspose-pdf/Aspose.PDF-for-.NET#55]
I tried to use the [PDF Editor](https://github.com/aspose-pdf/Aspose.PDF-for-.NET/tree/master/Showcases/aspose-pdf-editor/pdf-editor-mvc) but it seems that Adding text, images, and signatures to a PDF doesn't work

**Comment by armaanrustami** [comment]
Solved the issue with following changes in Shape.js :

`
function SavePdf() {
    $('#loadingModal').modal('show');
    let filename = 'image'.concat(currentPage).concat('.png');

    shapes2 = [];

    for (var i = 0; i < shapes.length; i++) {
        tempShape = {
            x: shapes[i].x,
            y: shapes[i].y,
            textWidth: shapes[i].textWidth,
            fontHeight: shapes[i].fontHeight,
            page: shapes[i].page,
            f: shapes[i].f,
            text: shapes[i].text,
            fontText: shapes[i].fontText,
            fontSize: shapes[i].fontSize,
            fontColor: shapes[i].fontColor,
            fontWeight: shapes[i].fontWeight,
            fontStyle: shapes[i].fontStyle,
            ratio: shapes[i].ratio,
            imfile: '',
            imName: shapes[i].imName,
            Itype: shapes[i].Itype,
            fieldType: shapes[i].fieldType
        };
        shapes2.push(tempShape);
    }
    wholedata = JSON.stringify(
        { 
            'shapes': shapes2, 
            'filename': filename, 
            'aspectRatio': ratio, 
            'documentId': documentId 
        });
    const jsonObj = JSON.parse(wholedata);

    jsonObj.shapes = jsonObj.shapes.map(shape => {
        for (const key in shape) {
            if (typeof shape[key] === 'number') {
                shape[key] = shape[key].toString();
            }
        }
        return shape;
    });

    const modifiedWholedata = JSON.stringify(jsonObj);
   

    $.ajax({
        type: 'POST',
        url: `${apiBaseUrl}shape/add`,
        data: modifiedWholedata,
        contentType: 'application/json; charset=utf-8',
        dataType: 'json',
        success: function () {
            $("#savingModal").fadeTo(2000, 500).slideUp(500, function () {
                $("#savingModal").slideUp(500);
            });
        },
        error: function (xhr, textStatus, error) {
            alertModal('Error: ', xhr, textStatus, error);
        }
    })
    .done(function () { $('#loadingModal').modal('hide'); });
}
function convertIntToStr(obj) {
    if (typeof obj === 'number') {
        return obj.toString();
    } else if (typeof obj === 'object') {
        for (const key in obj) {
            obj[key] = convertIntToStr(obj[key]);
        }
    }
    return obj;
}`

**Comment by ilyazhuykov** [comment]
As there's no updates and solution is provided by user, issue considered as resolved
