### ISSUE TITLE
how to use CustomSignHash delegate

### ISSUE THREAD

**Issue by haizzh** [aspose-pdf/Aspose.PDF-for-.NET#59]

**Comment by haizzh** [comment]
I want to use this class to implement the server signature, but I also need a certificate file, does anyone know how to use this class?

**Comment by arise-project** [comment]
Hello, @haizzh 

Let me describe CustomSignHash for you. 
With CustomSignHash, you have full control over the signing process. This can be particularly useful when you need to sign documents with keys that are not directly supported by the library or platform you are using. For example, you might have a custom key management system or a hardware security module (HSM) that you need to interface with.
CustomSignHash allows you to integrate with existing systems or protocols that already have a signing process in place. This can be useful when you need to ensure that the signing process is compatible with existing systems or standards.
Using a custom signing method can provide additional security by allowing you to implement specific security measures, such as secure key storage or additional cryptographic operations.
It is crucial to thoroughly test the custom signing method to ensure that it works as expected and that it does not introduce security vulnerabilities.

The CustomSignHash delegate is assigned to the CustomSignHash property of the PKCS7 object.
The PKCS7 object is used to sign the document at the specified location with the custom signing method.
In the provided code snippet, CustomSignHash is a delegate that represents a custom signing method for a digital signature.
It defines a delegate SignHash that takes a byte array (signableHash) as a parameter.
The signed data is returned by the delegate.

Usual steps in CustomSignHash, cou can implement:

1. Open certificate to sign with.
2. Extract the private key from the certificate
3. Import the private key into crypto service provider.
4  Sign input hash using crypto service provider and imported certificate.

```csharp
var inputPdf = "test.pdf";
            var inputP12 = "test.p12";
            var inputPfxPassword = "123456";
            var outputPdf = "signed.pdf";

            SignHash customSignHash = delegate (byte[] signableHash)
    {
        X509Certificate2 signerCert = new X509Certificate2(inputP12, inputPfxPassword, X509KeyStorageFlags.Exportable);
        using (RSACryptoServiceProvider rsaCSP = new RSACryptoServiceProvider())
        {
            // Extract the private key from the certificate
            byte[] privateKeyBytes = signerCert.GetRSAPrivateKey().ExportPkcs8PrivateKey();

            // Import the private key into the RSACryptoServiceProvider
            rsaCSP.ImportPkcs8PrivateKey(privateKeyBytes, out _);

            // Sign the hash with the private key
            byte[] signedData = rsaCSP.SignData(signableHash, HashAlgorithmName.SHA1, RSASignaturePadding.Pkcs1);
            return signedData;
        }
    };
            using (var sign = new PdfFileSignature())
            {
                sign.BindPdf(inputPdf);
                var pkcs7 = new PKCS7(inputP12, inputPfxPassword);
                pkcs7.CustomSignHash = customSignHash;

                sign.Sign(1, "reason", "cont", "loc", false, new System.Drawing.Rectangle(0, 0, 500, 500), pkcs7);
                sign.Save(outputPdf);
            }

            using (var sign = new PdfFileSignature())
            {
                sign.BindPdf(outputPdf);
                Assert.IsTrue(sign.VerifySignature("Signature1"));
            }
```

Here is another example that helps to find server cert in HSM to sign with:

```csharp
SignHash customSignHash = delegate (byte[] signableHash)
        {
            using (RSACryptoServiceProvider rsaCsp = new RSACryptoServiceProvider(cspParameters))
            {
                // Find the private key in the HSM by its thumbprint
                rsaCsp.ImportCspBlob(FindPrivateKeyByThumbprint(certificateThumbprint, providerName));

                // Sign the hash with the private key
                byte[] signedHash = rsaCsp.SignHash(signableHash, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
                return signedHash;
            }
        };
```

FindPrivateKeyByThumbprint method should be implemented according to the specifics of the HSM and CSP provider you are using.

**Comment by ilyazhuykov** [comment]
Since there have been no updates or additional questions for more than half a year, the issue is considered resolved
