### ISSUE TITLE
Text is always underlined on page if auto-wrapped

### ISSUE THREAD

**Issue by mur-dock** [aspose-pdf/Aspose.PDF-for-.NET#62]
**Describe the bug**
When adding a text fragment to the list of paragraphs of a page, the text is going to be underlined every time.
This only happen if the text is auto-wrapped into the next line.

**To Reproduce**
```csharp
        var document = new Aspose.Pdf.Document();
        var page = document.Pages.Add();

        // This text fragment is underlined in pdf
        page.Paragraphs.Add(new TextFragment("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, " +
                                             "sed diam nonumy eirmod tempor invidunt ut lab.") {
            TextState = {
                FontSize = 11,
                Font = FontRepository.FindFont("Arial"),
                HorizontalAlignment = HorizontalAlignment.Left,
                Underline = false, // <-- explicitly false
            },
        });

        // This text fragment is NOT underlined in pdf
        page.Paragraphs.Add(new TextFragment("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, " +
                                             "sed diam nonumy eirmod.") {
            TextState = {
                FontSize = 11,
                Font = FontRepository.FindFont("Arial"),
                HorizontalAlignment = HorizontalAlignment.Left,
                Underline = false, // <-- explicitly false
            },
        });

        // processing document...
        document.ProcessParagraphs();

        // end
        using var stream = File.Create("result.pdf");
        document.Save(stream);
```

**Expected behavior**
If I set `Underline` to `false`, the text should not be underlined.

**Screenshots**
![image](https://github.com/user-attachments/assets/1f876d44-0a18-423e-976c-e86f9b525eda)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - TargetFramework: net8.0
 - Browser: chrome
 - Version: Aspose.PDF 24.9.0

**Additional context**
The issue occurs in Aspose.PDF version from 24.6 to 24.9 but not in 24.5.

**Comment by arise-project** [comment]
Hello, @mur-dock 

Thank you for reporting this issue. I've created a bug for the Aspose.PDF team, but I was able to set it at a 'low' priority for now.

PDFNET-58388

If you have a valid license, I can update the priority to 'Paid customer' to expedite the resolution. Please let me know, and I'll make the necessary changes.

Thank you!

**Comment by mur-dock** [comment]
> Hello, @mur-dock
> 
> Thank you for reporting this issue. I've created a bug for the Aspose.PDF team, but I was able to set it at a 'low' priority for now.
> 
> PDFNET-58388
> 
> If you have a valid license, I can update the priority to 'Paid customer' to expedite the resolution. Please let me know, and I'll make the necessary changes.
> 
> Thank you!

Thank you very much, @arise-project .
How can I verify that I have a "paid license"?
The license is binded to my company.

**Comment by arise-project** [comment]
Hello, @mur-dock , priority changed to 'Paid Customer'

**Comment by ilyazhuykov** [comment]
PDFNET-58388 is resolved, therefore issue is closed
