### ISSUE TITLE
.NET 8 PDF to picture  is not suppoted in Linux platform

### ISSUE THREAD

**Issue by JohnnyJiang2021** [aspose-pdf/Aspose.PDF-for-.NET#64]
In .net8, using Aspose.PDF to convert PDF to picture on linux platform is not supported

[Error Picture](https://github.com/user-attachments/assets/bcfd2692-0d86-4b8d-be53-f3bfa8097922)

**Comment by arise-project** [comment]
Hello, @JohnnyJiang2021 ,

I recommend using the Aspose.PDF.Drawing package for Linux, as it does not depend on System.Drawing. You can apply the same license you have for the Aspose.PDF package, which is primarily for Windows.

You can find the package here: [Aspose.PDF.Drawing NuGet](https://www.nuget.org/packages/Aspose.PDF.Drawing/24.10.0).

If you’ve already encountered an issue with Aspose.PDF.Drawing, could you please provide a code snippet and a sample file that you’re unable to convert? This will help us assist you more effectively.

Thank you!
